src/alfresco-core-rest-api/src/ApiClient.js
Ref Cannot upload file in Safari 660
=> Fix Safari file check

CHANGELOG.md, index.d.ts
```
[x ] Tests for the changes have been added (for bug fixes / features)
```
```
[x ] Bugfix
[ ] Feature
```
The parameter in the object AlfrescoApiConfig are not optional in the declaration file that make …
=> make AlfrescoApiConfig parameters optional

package.json
Allows using both within node.js and browser environments by specifying "browser" target that can be used for bundlers, like Webpack: https://webpack.js.org/configuration/resolve/#resolve-mainfields
```
```
```
[ ] Bugfix
[x] Feature
```
**What is the …
=> add "browser" target to fix bundling issues

CHANGELOG.md, index.d.ts
```
```
```
[ ] Bugfix
[ ] Feature
[ x] Other... Please describe:
```
NodePagingList type should include optional "source" property #211 …
=> NodePagingList type should include optional "source" property #211

CHANGELOG.md, src/alfresco-activiti-rest-api/src/api/TaskFormsApi.js, test/mockObjects/activiti/taskFormMock.js
```
```
```
[x ] Bugfix
[ ] Feature
```
move from rest to enterprise task-forms variables api …
=> #199 - move from rest to enterprise task-forms variables api

CHANGELOG.md, src/alfrescoContent.js, test/contet.spec.js
```
```
```
[ ] Bugfix
[x] Feature
```
No possible option to retrieve a rendition's url from the content API.
getRenditionUrl of the …
=> [ADF-793] The ability to retrieve a rendition's url from the content API

CHANGELOG.md, index.d.ts, src/alfresco-activiti-rest-api/README.md, src/alfresco-activiti-rest-api/docs/TaskApi.md, src/alfresco-activiti-rest-api/docs/TaskAuditRepresentation.md, src/alfresco-activiti-rest-api/src/api/TaskApi.js, src/alfresco-activiti-rest-api/src/model/TaskAuditRepresentation.js
-getTaskAuditJson
-getTaskAuditPdf
```
```
```
[ ] Bugfix
[x] Feature
```
The Audit task logs endpoints are missing
Add the Audit task logs …
=> Add Audit task logs endpoints

CHANGELOG.md, src/alfresco-activiti-rest-api/src/api/UserApi.js
```
```
```
[X] Bugfix
[] Feature
```
Nothing is returned for userApi getProfilePicture
a blob is returned for the image of getProfilePicture …
=> [ADF-1083] added responseType to getProfile image for user api

CHANGELOG.md, package-lock.json, src/bpmAuth.js, src/ecmAuth.js
```
```
```
[x] Bugfix
[ ] Feature
```
Upon page reload the username is lost and all the code that relies on that stops working.
Preserve the …
=> [ADF-1523] preserve username between page reloads

CHANGELOG.md, index.d.ts
```
```
```
[x] Bugfix
[ ] Feature
```
https://issues.alfresco.com/jira/browse/ADF-1829 …
=> [ADF-1829] PeopleApi - getSiteMembership wrong returned type

CHANGELOG.md, index.d.ts, src/alfresco-activiti-rest-api/src/api/ContentApi.js
Addresses bugs:
- [ADF-1962: getContentThumbnailUrl returns file data instead or URL](https://issues.alfresco.com/jira/browse/ADF-1962)
- [ADF-1963: ContentApi is missing the preview rendition API](https://issues.alfresco.com/jira/browse/ADF-1963)
=> [ADF-1963] content api fixes

CHANGELOG.md, index.d.ts, src/alfrescoContent.js, test/alfrescoContent.spec.js
```
```
```
[ ] Bugfix
[x] Feature
```
provides utility method to generate content url for a shared link …
=> [ADF-2136] generating shared link content url

CHANGELOG.md, README.md, src/alfrescoApi.js, src/oauth2Auth.js, test/mockObjects/oauth2/authResponseMock.js, test/oauth2Auth.spec.js
```
```
```
[x] Bugfix
[ ] Feature
```
The auth2 API is passing the value through the queryParam
The auth2 API is passing the value through the …
=> [ADF-2288] Auth2 endpoint - Use parameForm instead of queryForm

index.d.ts
```
[n/a] Tests for the changes have been added (for bug fixes / features)
[n/a] Docs have been added / updated (for bug fixes / features)
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Just a minor update to index.d.ts
```
TypeScript compiler complains about missing 'id' property on UserRepresentation (#307)
**What is …
=> Adding the id property to the UserRepresentation typing

CHANGELOG.md, index.d.ts
```
```
```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
RequestPagination had the wrong types for skipCount and maxItems
Changed the types from string to number …
=> [ADF-2448] fixed type for RequestPagination

index.d.ts
```
```
```
[x] Bugfix
[ ] Feature
```
In index.d.ts:
* The `FormDefinitionRepresentation.fields` and `FormFieldRepresentation.options` types are not arrays.
* The return …
=> Adding a couple of missing semicolons and Activiti types

package.json
<a name="2.3.0"></a>
[Update search api](https://issues.alfresco.com/jira/browse/ADF-2493)
[Add groups api](https://issues.alfresco.com/jira/browse/ADF-2570)
[Upate version api with missing endpoint](https://issues.alfresco.com/jira/browse/ADF-2558)
[Wrong type definition for RequestPagination](https://issues.alfresco.com/jira/browse/ADF-2448)
[Not able to log-in into BPM with production mode and CSRF token enable](https://github.com/Alfresco/alfresco-js-api/issues/315)
[Search api type definition is not defined](https://issues.alfresco.com/jira/browse/ADF-2450)
[Incorrect definitions for Enums](https://issues.alfresco.com/jira/browse/ADF-2604)
[Search API implementation is incomplete](https://issues.alfresco.com/jira/browse/ADF-2470)
=> 2.3.0 bump version (#325)

CHANGELOG.md, index.d.ts, src/alfresco-core-rest-api/src/api/NodesApi.js, src/alfrescoUpload.js
```
```
```
[ ] Bugfix
[X] Feature
```
https://issues.alfresco.com/jira/browse/ADF-2563
Now is possible update a node content using the content update call
**What is the new …
=> [ADF-2563] Update node content

index.d.ts
```
```
```
[x] Bugfix
[ ] Feature
```
The type definition for `TaskFormsApi.getTaskFormVariables` has `FormDefinitionRepresentation` as a return type.
**What is the new …
=> Fix type definition for TaskFormsApi.getTaskFormVariables

CHANGELOG.md, index.d.ts, scripts/test-demo-shell-adf.sh, src/alfresco-activiti-rest-api/src/api/AppsApi.js, src/alfresco-activiti-rest-api/src/api/AppsDefinitionApi.js, src/alfresco-core-rest-api/src/ApiClient.js
```
```
```
[x] Bugfix
[ ] Feature
```
https://issues.alfresco.com/jira/browse/ADF-3289 …
=> [ADF-3289] AppsDefinitionApi contains two methods with same name and different firms

CHANGELOG.md, index.d.ts, src/alfresco-core-rest-api/src/model/PathElement.js
```
```
```
[x] Bugfix
[ ] Feature
```
- fix typings
- add missing properties for path element …
=> [ADF-3214] path element fixes

package.json, src/oauth2Auth.js, webpack.config.js
remove validation client side
```
```
```
[x] Bugfix
[ ] Feature
```
Remove Comments
Remove Validation …
=> fix build issues

README.md, src/oauth2Auth.js
```
```
```
[x] Bugfix
[ ] Feature
```
When the silent login is enabled the app is freezing 
The app should be able to renew the token through …
=> [ADF-3531] Fix the silent refresh login

src/oauth2Auth.js
```
```
```
[ ] Bugfix
[ ] Feature
```
we remove always the hash part but it could be a valid angular route
we remove the hash only if is not a …
=> [ADF-3552] OAuth - Should not remove the hash part if is a valid route

CHANGELOG.md, index.d.ts
```
```
```
[x] Bugfix
[ ] Feature
```
"versionComment" is missing in typings
"versionComment" is present in typings …
=> [ADF-3155] "versionComment" is missing in typings

src/oauth2Auth.js
```
```
```
[X] Bugfix
[ ] Feature
```
When not enabled implicit flow access token is never stored in the local storage. This makes the guard considering you not logged in …
=> [ADF-3538] added access token storaging for no implicit flow behaviour

src/authentication/oauth2Auth.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Steps to reproduce the issue:
Login with SSO, implicitFlow false
Current behaviour:
Session is not kept …
=> [ADF-3648] add silent refresh in grant password

README.md, src/alfrescoApi.ts, src/alfrescoApiCompatibility.ts, test/oauth2Auth.spec.ts, test/peopleApi.spec.ts
```
```
```
[ ] Bugfix
[x] Feature
```
With the new version of the JS-API we have lost the possibility to configure the JS-API during the construction.
With this PR I have …
=> Add double possibility to configure the JS-API also in the constructor

src/api/content-rest-api/api/webscript.api.ts
```
```
```
[X] Bugfix
[ ] Feature
```
check #394 
Fix method declaration
``` …
```
=> #394 Fix method signature

src/authentication/oauth2Auth.ts
```
```
```
[x] Bugfix
[ ] Feature
```
The discovery SSO configuration is not deleted over a server discovery error
I discovered it meanwhile I was trying to add some …
=> [ADF-3735] clean discovery storage over an error

src/authentication/oauth2Auth.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Not able to login with implicit flow false. An authHeader is added to the request
Able to login with …
=> [ADF-4165] SSOLogin - Fix the implicitFlow false

src/alfrescoApi.ts
```
```
```
[x] Bugfix
[ ] Feature
```
node:6386) UnhandledPromiseRejectionWarning: #<Object>
[chrome #01-1] (node:6386) UnhandledPromiseRejectionWarning: Unhandled promise …
=> UnhandledPromiseRejectionWarning fix

src/alfrescoApi.ts, src/authentication/oauth2Auth.ts, test/oauth2Auth.spec.ts, test/oauth2AuthImplicitFlow.spec.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Different instance of JS-API should have difference instance of the Oauth2 Client
**Does this PR …
=> oauth2  should not be static

src/authentication/oauth2Auth.ts, test/oauth2Auth.spec.ts
```
```
```
[X] Bugfix
[ ] Feature
```
We try to always retrieve the ECM ticket on OAUTH2 even when Content is not available.
We prevent the …
=> Fixing exchange ticket based on provider

src/alfrescoApiClient.ts, src/authentication/processAuth.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Log in to ADF Process services and create a new Task in the Task app.
Check the browser console.
Current behaviour:
There is an error …
=> [ADF-5056] use user agent only in aps auth

src/alfrescoApiClient.ts, src/authentication/processAuth.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Steps to reproduce the issue:
Log in to ADF Process services and create a new Task in the Task app.
Check the browser console.
Current behaviour:
There is an error in the Console => 'Refused to set unsafe header …
=> [ADF-5006] Fix user agent warning 

src/api/content-rest-api/docs/Tag.md, src/api/content-rest-api/model/tag.ts
```
```
```
[ ] Bugfix
[x] Feature
```
No count property for the Tag model.
The count property is needed when using the use of `include=count` …
=> [ADF-155] Add count optional property to tag model

src/api-legacy/content-rest-api/src/api/tagsApi.ts, src/api/content-rest-api/api/tags.api.ts
See issue #628
I also can't build my project with webpack because of that issue.
REST API works with both a single TagBody and a TagBody array, so it's a simple matter of allowing the array type in the function signature.
`createTagForNode` and the legacy `addTag` accept a single TagBody as well as an array. 
**Other information**:
As I mentioned at the beginning, I didn't create tests because I can't even run the existing tests with `npm test`:
``` …
```
=> Accept BodyTag array in createTagForNode

src/api-legacy/activiti-rest-api/docs/TaskApi.md, src/api-legacy/activiti-rest-api/src/api/TaskApi.ts, src/api/activiti-rest-api/api/tasks.api.ts
```
```
```
[x] Bugfix
[ ] Feature
```
https://issues.alfresco.com/jira/browse/AAE-2261
done …
=> [AAE-2261] [ADF] can't open the downloaded task audit file

src/api/content-rest-api/api/content.api.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
https://issues.alfresco.com/jira/browse/ACA-100
Added a new method to retrieve a node's version's …
=> [ACA-100] View a previous version

src/api/content-rest-api/api/content.api.ts, test/alfrescoContent.spec.ts
…it tests for the 2 new methods.
```
```
```
[ ] Bugfix
[ ] Feature
```
https://issues.alfresco.com/jira/browse/ACA-100
Now I have a method that …
=> [ACA-100] New method to retrieve a node's version's content

package.json, tools/rollup-bundle.js
```
```
```
[ ] Bugfix
[ ] Feature
```
Do not bundle the following external dependencies:
- superagent
- minimatch
- event-emitter
Reduce the …
=> reduce umd bundle size by 16%

src/alfrescoApiClient.ts, src/api/activiti-rest-api/api/processInstances.api.ts, src/api/activiti-rest-api/model/systemPropertiesRepresentation.ts, src/authentication/contentAuth.ts, src/authentication/oauth2Auth.ts
```
```
```
[x] Bugfix
[ ] Feature
```
workaround for minimatch to support old versions of typescript and ng-packgr …
=> workaround for minimatch

src/alfrescoApiClient.ts
```
```
```
[ ] Bugfix
[x] Feature
```
provides support for `url` parameter (emulating the `callCustomApi` calls) with the generic methods …
=> support custom api calls with generic api

src/authentication/oauth2Auth.ts, test/oauth2Auth.spec.ts
```
[x ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-js-api/wiki/Commit-format)
```
```
[x] Bugfix
[ ] Feature
```
In general, node wait for all timeouts and interval to finish before to end the app unless we unrefer it …
=> Fix hang setinterval for missing logout

src/authentication/oauth2Auth.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Avoid save token when nonce is invalid and emit error …
=> Avoid save token when nonce is invalid and emit error

src/authentication/oauth2Auth.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
We don't get the access token from the storage when init the js-api if si not in silent login, that is a problem when this mode is on …
=> Fix refresh when in not silent mode

src/authentication/oauth2Auth.ts, test/oauth2AuthImplicitFlow.spec.ts
```
```
```
[x] Bugfix
[ ] Feature
```
The iframe for refresh the token doesn't get create once you refresh your browser
The iframe for refresh …
=> [AAE-4745] Add iframe for refresh the token when we refresh the browser

src/authentication/oauth2Auth.ts, test/oauth2AuthImplicitFlow.spec.ts
```
```
```
[x] Bugfix
[ ] Feature
```
when you get redirected the redirect removes everything after the first ampersand.
when you get …
=> [MNT-22286] Fix cut params on redirect

.make-packages.js, test/performance/test-webpack/package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
=> fix(packaging): move typings in a separate folder to allow consuming

src/api/content-rest-api/api/nodes.api.ts
https://github.com/Alfresco/alfresco-js-api/issues/903
```
```
```
[x] Bugfix
[ ] Feature
```
https://github.com/Alfresco/alfresco-js-api/issues/903
**What is the new …
=> (fix) getNodeContent throwing error 

.eslintignore, .eslintrc.js, package-lock.json, package.json, scripts/lint.sh, src/alfrescoApiClient.ts, src/api/activiti-rest-api/api/report.api.ts, src/authentication/oauth2Auth.ts, test/content-services/queriesApi.spec.ts
```
```
```
[ ] Bugfix
[x] Feature
```
- integrate ESLint (works great with VS Code extension: …
=> ESLint support

package-lock.json, package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
add missing `tslib` dependency, as by default the compilation includes the TS helpers
fixes #1352
```
[ ] Yes
[x] …
```
=> add missing tslib dependency

src/alfrescoApi.ts, test/alfrescoApi.spec.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Description is provided here -> https://alfresco.atlassian.net/browse/MNT-23143
withCredentials param is …
=> [MNT-23143] withCredentials reflected in isBpmLoggedIn

src/api/content-rest-api/api/categories.api.ts, src/api/content-rest-api/docs/CategoriesApi.md, src/api/content-rest-api/docs/Category.md, src/api/content-rest-api/docs/CategoryBody.md, src/api/content-rest-api/docs/CategoryEntry.md, src/api/content-rest-api/docs/CategoryLinkBody.md, src/api/content-rest-api/docs/CategoryPaging.md, src/api/content-rest-api/docs/CategoryPaging_list.md, src/api/content-rest-api/model/CategoryLinkBody.ts, src/api/content-rest-api/model/category.ts, src/api/content-rest-api/model/categoryBody.ts, src/api/content-rest-api/model/categoryEntry.ts, src/api/content-rest-api/model/categoryPaging.ts, src/api/content-rest-api/model/categoryPagingList.ts
```
```
```
[ ] Bugfix
[x] Feature
```
There is no categories api. https://alfresco.atlassian.net/browse/ACS-4114
Categories aoi has been added …
=> [ACS-4114] Add categories api

src/api/content-rest-api/api/categories.api.ts, src/api/content-rest-api/docs/CategoriesApi.md, src/api/content-rest-api/docs/CategoryLinkBody.md, src/api/content-rest-api/model/CategoryLinkBody.ts, test/content-services/categoriesApi.spec.ts, test/mockObjects/content-services/categories.mock.ts
```
```
```
[ ] Bugfix
[x] Feature
```
Categories API was untested. https://alfresco.atlassian.net/browse/ACS-4231
Unit tests covering each …
=> [ACS-4231] Add unit tests to categories API

.github/workflows/codeql-analysis.yml, .github/workflows/js-api-build.yml, .github/workflows/trigger-upstream.yml
```
```
```
[x] Bugfix
[ ] Feature
```
Switch to latest setup-node and node 16
Fix GHA warnings for the upcoming deprecations:
Node.js 12 …
=> Fix GHA warnings for upcoming changes for setup-node action

src/storage.ts
```
```
```
[x] Bugfix
[ ] Feature
```
sessionStorage is checked instead of localStorage.
localStorage is now used instead.
**Does this PR …
=> [ACS-4611] Check proper storage

scripts/update-project.sh
When install the new version of the JS-API the lock file in ADF needs to be version 1
```
```
```
[ ] Bugfix
[ ] Feature
```
**Does this PR …
=> fix-js-api-upstream

.github/workflows/js-api-build.yml, scripts/publish.sh
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
=> Npm publish: Use token as part of workflow

README.md, src/alfrescoApi.ts, src/alfrescoApiConfig.ts
…when the new oidc auth is used on adf
```
```
```
[ ] Bugfix
[x] Feature
```
https://alfresco.atlassian.net/browse/AAE-12501
A new property …
=> [AAE-12501] Align JS API

src/api/content-rest-api/api/tags.api.ts, test/content-services/tagApi.spec.ts, test/mockObjects/content-services/tag.mock.ts
```
```
```
[x] Bugfix
[ ] Feature
```
https://alfresco.atlassian.net/browse/ACS-4753
Added possibility to load tags not only by exact matching …
=> [ACS-4753] list of tags is not rendered because of missing count field in backend response

src/api/content-rest-api/api/categories.api.ts, src/api/content-rest-api/docs/Category.md, src/api/content-rest-api/model/category.ts, test/content-services/categoriesApi.spec.ts, test/mockObjects/content-services/categories.mock.ts
```
```
```
[ ] Bugfix
[x] Feature
```
There is not option to get path for categories. https://alfresco.atlassian.net/browse/ACS-4966
Category …
=> [ACS-4966] Add path to category model

src/api/gs-core-rest-api/api/files.api.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
https://github.com/Alfresco/alfresco-js-api/issues/1582
add missing query param for declareRecord, fixes …
=> fix missing parentId for declareRecord

src/alfrescoApi.ts, src/alfrescoApiClient.ts, src/authentication/contentAuth.ts, src/authentication/oauth2Auth.ts, src/authentication/processAuth.ts, src/storage.ts, test/oauth2Auth.spec.ts, test/oauth2AuthImplicitFlow.spec.ts
…t in not added to the content api because config.ticketECM is undefined
```
```
```
[ ] Bugfix
[ ] Feature
```
Moving basic auth in ADF …
=> [AAE-12502] Fix ticketEcm is not added to the alf_ticket moving basic auth in ADF

src/alfrescoApiConfig.ts, src/api-clients/http-client.interface.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
Make `contextRoot` optional as per documentation …
=> [ACS-5839] Make `contextRoot` optional as per documentation

src/api/content-rest-api/docs/SiteEntry.md, src/api/content-rest-api/docs/SiteEntryRelations.md, src/api/content-rest-api/model/siteEntryRelations.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
Added missing relations to SiteEntry. …
=> Add relations to site entry

package-lock.json, package.json, test/oauth2Auth.spec.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
Use jsdom directly instead of deprecated mocha-jsdom to fix and re-enable excluded unit test. …
=> [ACA-4724] Use jsdom directly instead of mocha-jsdom in unit test
