- src/alfresco-core-rest-api/src/ApiClient.js
> Fix bug null date

- index.d.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> improve description file

- .babelrc
- .npmignore
- CHANGELOG.md
- package.json
```
```
```
[x] Bugfix
[ ] Feature
```
added some plugin for babel to extend the compatibility for IE10 …
> #121 - fix babelify for IE10

- CHANGELOG.md
- src/alfresco-activiti-rest-api/src/api/ScriptFileApi.js
```
```
```
[x ] Bugfix
[ ] Feature
```
#130
```
[ ] Yes
[ ] No
```
If this PR …
> #130 fix header controllers api

- CHANGELOG.md
- index.d.ts
```
```
```
[x] Bugfix
[ ] Feature
```
https://github.com/Alfresco/alfresco-js-api/issues/139 …
> #139 Wrong PathInfoEntity declaration

- CHANGELOG.md
- src/bpmAuth.js
- src/ecmAuth.js
- test/bpmAuth.spec.js
- test/ecmAuth.spec.js
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> Ticket not cleaned when host is changed  143

- CHANGELOG.md
- src/alfrescoApi.js
- test/auth.spec.js
- test/bpmAuth.spec.js
- test/ecmAuth.spec.js
- test/upload.spec.js
- test/webScriptApi.spec.js
```
```
```
[x] Bugfix
[ ] Feature
```
https://github.com/Alfresco/alfresco-js-api/issues/153 …
> #153 remove UnhandledPromiseRejectionWarning in the test log

- CHANGELOG.md
- README.md
- src/alfresco-activiti-rest-api/docs/ReportApi.md
- src/alfresco-activiti-rest-api/src/api/ReportApi.js
- src/alfresco-activiti-rest-api/src/model/ReportDateRangeRepresentation.js
- src/alfresco-activiti-rest-api/src/model/ReportExportQueryRepresentation.js
- src/alfresco-activiti-rest-api/src/model/ReportSaveQueryRepresentation.js
- test/activitiReportApi.spec.js
- test/mockObjects/activiti/reportsMock.js
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> #164 - Added new api to export - delete and save the report

- package.json
- src/alfresco-core-rest-api/src/ApiClient.js
```
```
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
If this PR …
> fix package.json #166

- index.d.ts
> Add additional methods and make opts optional

- src/bpmAuth.js
- test/bpmAuth.spec.js
- test/ecmAuth.spec.js
```
[x ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-js-ap/wiki/Commit-format)
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> Dev eromano auth

- CHANGELOG.md
- src/alfresco-core-rest-api/docs/CommentsApi.md
- test/commentsApi.spec.js
- test/mockObjects/alfresco/CommentMock.js
- test/mockObjects/mockAlfrescoApi.js
```
```
```
[ ] Bugfix
[ ] Feature
[x ] Documentation
```
documentation comments Api fix #214  …
> fix documentation comments Api#214

- CHANGELOG.md
- src/alfresco-activiti-rest-api/src/api/TaskFormsApi.js
- test/mockObjects/activiti/taskFormMock.js
```
```
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> #217 - revert changes from #65

- CHANGELOG.md
- src/alfrescoApi.js
- src/alfrescoApiClient.js
- test/alfrescoApi.spec.js
- test/auth.spec.js
- test/mockObjects/activiti/profileMock.js
- test/mockObjects/alfresco/nodeMock.js
- test/mockObjects/baseMock.js
```
```
```
[x ] Bugfix
[ ] Feature
```
#210
```
[ ] Yes
[ ] No
```
If this …
> invalidate ticket when receive 401 #210

- CHANGELOG.md
- index.d.ts
- src/bpmAuth.js
- src/ecmAuth.js
- test/bpmAuth.spec.js
- test/ecmAuth.spec.js
> [ADF-563] remember/forget username

- .npmignore
- package.json
```
[x ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-js-ap/wiki/Commit-format)
[x ] Tests for the changes have been added (for bug fixes / features)
```
```
[ ] Bugfix
[x ] Feature
```
Add prepublish script
```
[ ] Yes
[ …
```
> add prepublish task

- CHANGELOG.md
- src/alfresco-activiti-rest-api/docs/ContentApi.md
- src/alfresco-activiti-rest-api/src/api/ContentApi.js
```
```
```
[X] Bugfix
[ ] Feature
```
Even not related contents are returned because no query parameter is sent to the enterprise api
Only …
> [ADF-684] added query parameter to retrieve related content for task and process

- index.d.ts
Missing declaration for the previous PR.
> [ADF-793] Missing declaration

- index.d.ts
Fixing tslint error for ADF-793 PR.
> [ADF-793] Fixing tslint error

- index.d.ts
```
```
```
[x ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> Fix tslint errros

- CHANGELOG.md
- index.d.ts
```
[x ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-js-ap/wiki/Commit-format)
[x ] Tests for the changes have been added (for bug fixes / features)
[x ] Docs have been added / updated (for bug fixes / features)
```
```
[x ] Bugfix
[ ] Feature
```
https://issues.alfresco.com/jira/browse/ADF-943
https://issues.alfresco.com/jira/browse/ADF-943
**Does …
> APS ContentApi is not present on index.d.ts and SitesApi is not complete

- .gitignore
- CHANGELOG.md
- src/alfresco-auth-rest-api/src/api/AuthenticationApi.js
- src/ecmAuth.js
```
```
```
[x] Bugfix
[ ] Feature
```
See ticket ADF-978 and ADF-1200
In case of wrong urls, we handle the errors properly.
**Does this PR …
> [ADF-1200] Error handling for wrong host urls

- CHANGELOG.md
- src/alfresco-activiti-rest-api/docs/ProcessApi.md
- src/alfresco-activiti-rest-api/docs/ProcessInstanceAuditRepresentation.md
- src/alfresco-activiti-rest-api/src/api/ProcessApi.js
- src/alfresco-activiti-rest-api/src/model/ProcessInstanceAuditRepresentation.js
```
```
```
[ ] Bugfix
[x] Feature
```
The Process audit log end points are missing
getProcessAuditJson
getProcessAuditPdf
**Does this PR …
> Add Process Audit Log end points

- CHANGELOG.md
- src/alfresco-core-rest-api/src/api/FavoritesApi.js
Fix issue with passing "include" settings in Favorites Api
> [ADF-1394] fix favorites api

- CHANGELOG.md
- index.d.ts
```
```
```
[x] Bugfix
[ ] Feature
```
https://issues.alfresco.com/jira/browse/ADF-1535
https://issues.alfresco.com/jira/browse/ADF-1535
**Does …
> [ADF-1535] fix StatusEnum Rendition service

- CHANGELOG.md
- src/alfresco-activiti-rest-api/src/api/UserApi.js
```
```
```
[x] Bugfix
[ ] Feature
```
Fix the generation for profile image URL …
> [ADF-1559] fix profile picture url bug

- CHANGELOG.md
- src/alfresco-activiti-rest-api/src/api/UserApi.js
```
```
```
[ ] Bugfix
[ ] Feature
```
Rollback previous change
```
[ ] Yes
[ …
```
> [ADF-1559] rollback the change due to API issues

- src/alfresco-activiti-rest-api/docs/UserApi.md
```
```
```
[ ] Bugfix
[ ] Feature
[X] Documentation
```
```
[ ] Yes
[ ] No
```
If this PR …
> [ADF - 1641] fixed documentation for getUserProfilePictureUrl

- CHANGELOG.md
- index.d.ts
- fix typings issues
- remove duplicate properties
- remove duplicate interfaces
> [ADF-1678] cleanup typings schema

- src/alfrescoApiClient.js
fix a bug with file content streaming when using node.js
refs #271
> [ADF-1737] fix for node.js streaming

- README.md
- index.d.ts
```
[X] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-js-ap/wiki/Commit-format)
```
```
[ ] Bugfix
[x] Feature
```
https://issues.alfresco.com/jira/browse/ADF-1004 …
> [ADF-1004] d.ts process service

- package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
update superagent version
update superagent version …
> update superagent version

- .vscode/settings.json
- CHANGELOG.md
- index.d.ts
- src/alfrescoNode.js
```
```
```
[x] Bugfix
[ ] Feature
```
**What is the current behaviour?** (You can also link to an open issue here)
**What is the new behaviour?**
- Update type definition to reflect actual return types.
- Fix typos in parameters and api names.
**Does …
> [ADF-1860] update NodesApi definition

- CHANGELOG.md
- index.d.ts
- src/alfresco-activiti-rest-api/docs/ModelJsonBpmnApi.md
- src/alfresco-activiti-rest-api/src/api/ModelJsonBpmnApi.js
- tslint.json
```
```
```
[ ] Bugfix
[x] Feature
```
getModelJSON
getModelJSONForProcessDefinition …
> [ADF-1800] add new methods: getModelJSON getModelJSONForProcessDefinition

- index.d.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
QueryBody model is not exported into index.d.ts
QueryBody model is now exported into index.d.ts
**Does …
> [ADF-1933] added QueryBody to the index.d.ts

- index.d.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> [ADF-1933] name should be QueryBody not QueryNode

- CHANGELOG.md
- index.d.ts
- src/alfresco-core-rest-api/src/api/RenditionsApi.js
- src/alfrescoContent.js
- test/alfrescoContent.spec.js
```
```
```
[x] Bugfix
[ ] Feature
```
- adds missing API (get single rendition)
- improves Typescript definition schema
**Does this PR introduce …
> [ADF-2136] typings and api fixes for shared links

- CHANGELOG.md
- index.d.ts
- package.json
- src/alfresco-core-rest-api/README.md
- src/alfresco-core-rest-api/docs/PeopleApi.md
- src/alfresco-core-rest-api/src/api/PeopleApi.js
- test/content-services/peopleApi.spec.js
- test/mockObjects/content-services/peopleMock.js
```
```
```
[x] Bugfix
[x] Feature
```
the /people endpoint is not present
Adding the /people endpoint to the AlfrescoCoreRestApi.PeopleApi …
> Adding the /people endpoint to the AlfrescoCoreRestApi.PeopleApi

- README.md
```
```
```
[ ] Bugfix
[ ] Feature
```
Incorrectly referencing wrong npm package whenever using Node installation of client.
Missing hyphen from `npm install` command.
**What …
> Updating minor issues within documentation

- src/alfrescoUpload.js
```
```
```
[x] Bugfix
[x] Feature
```
See https://issues.alfresco.com/jira/browse/ADF-2368
Fixed …
> [ADF-2368] Add optional name param to file upload

- CHANGELOG.md
- index.d.ts
```
```
```
[X] Bugfix
[ ] Feature
```
missing type for search api in declaration file
Added searchApi type to declaration file.
**Does this PR …
> [ADF-2450] add declaration for search api

- .github/PULL_REQUEST_TEMPLATE.md
```
[ ] Bugfix
[ ] Feature
```
Links broken.
Links fixed.
```
[ ] Yes
[x] No
```
> Fix typo in URLs

- CHANGELOG.md
- index.d.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Fixes for `index.d.ts`
- [Incorrect definitions for …
> type definition fixes

- package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
Update package.json to 2.3.0
```
[ ] …
```
> 2.3.0 bump version

- CHANGELOG.md
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> Publish the release 2.3.1 for compatibility reason

- CHANGELOG.md
- index.d.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Added missing Search-related typings …
> [ADF-2885] add missing search typings

- index.d.ts
- scripts/test-demo-shell-adf.sh
- src/alfrescoApi.js
```
```
```
[x] Bugfix
[ ] Feature
```
Fix enums that are used from the global scope when importing to TypeSript …
> fix enums usage/imports in TypeScript

- CHANGELOG.md
- index.d.ts
- src/alfresco-core-rest-api/src/model/NodeMinimal.js
```
```
```
[ ] Bugfix
[x] Feature
```
- add new "isFavorite" field based on https://issues.alfresco.com/jira/browse/ACE-1683
**Does this PR …
> [ADF-3037] Add newly introduced isFavorite property to Nodes

- CHANGELOG.md
- README.md
- src/alfresco-core-rest-api/src/ApiClient.js
```
```
```
[x] Bugfix
[ ] Feature
```
disable upload timeout
```
[ ] Yes
[ ] …
```
> [ADF-2481] disable timeout

- CHANGELOG.md
- index.d.ts
- src/alfresco-core-rest-api/src/model/NodeMinimal.js
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> [ADF-3063] Shared node - nodeId property

- CHANGELOG.md
- index.d.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Update `index.d.ts` with missing information …
> [ADF-2603] getVersionContent type definition missing parameters

- src/oauth2Auth.js
```
```
```
[x] Bugfix
[ ] Feature
```
clean the hash parameters after the redirect
check if the hash is a valid angular route
**Does this PR …
> Fix oauth2 hash problems

- CHANGELOG.md
- index.d.ts
- src/alfrescoApi.js
- src/bpmAuth.js
- src/ecmAuth.js
```
```
```
[x] Bugfix
[ ] Feature
```
[ADF-3224] move logic store ticket in alfresco-js-api …
> [ADF-3224] move logic store ticket in alfresco-js-api

- .travis.yml
- src/oauth2Auth.js
- test/mockObjects/oauth2/authResponseMock.js
- test/oauth2Auth.spec.js
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> Dev build fix

- CHANGELOG.md
- index.d.ts
- src/alfresco-core-rest-api/README.md
- src/alfresco-core-rest-api/docs/ChangesApi.md
- src/alfresco-core-rest-api/docs/SitesApi.md
- src/alfresco-core-rest-api/src/api/ChangesApi.js
- src/alfresco-core-rest-api/src/api/SitesApi.js
```
[x ] Docs have been added / updated (for bug fixes / features)
```
```
[ ] Bugfix
[x] Feature
```
https://issues.alfresco.com/jira/browse/ADF-3366 …
> [ADF-3366] update Site details

- CHANGELOG.md
- index.d.ts
- src/alfresco-core-rest-api/README.md
- src/alfresco-core-rest-api/docs/PeopleApi.md
- src/alfresco-core-rest-api/docs/PersonBodyUpdate.md
- src/alfresco-core-rest-api/src/api/PeopleApi.js
```
```
```
[ ] Bugfix
[x] Feature
```
https://issues.alfresco.com/jira/browse/ADF-3412 …
> [ADF-3412] add updatePerson to peopleApi

- src/alfresco-core-rest-api/src/ApiClient.js
```
```
```
[x] Bugfix
[ ] Feature
```
Complex values (objects, arrays) are parsed to string as `[object Object]`.
Fixes: …
> [MNT-19911] correctly resolve object values in properties

- .travis.yml
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> Improve build stages travis

- index.d.ts
```
```
```
[ ] Bugfix
[x] Feature
```
https://issues.alfresco.com/jira/browse/APM-432
Exposed …
> [APM-432] - Add callCustomApi to index.d.ts

- src/alfrescoApi.js
- src/oauth2Auth.js
```
```
```
[x] Bugfix
[ ] Feature
```
See https://issues.alfresco.com/jira/browse/APM-433 and https://github.com/Alfresco/alfresco-modeler-app/pull/230/files
**What is the …
> Fix thrown error when using Oauth2's logOut method

- index.d.ts
- src/alfresco-activiti-rest-api/src/api/AppsApi.js
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> Added updateAppDefinition

- README.md
- src/alfrescoApi.js
- src/alfrescoApiClient.js
- test/alfrescoApi.spec.js
```
```
```
[ ] Bugfix
[x] Feature
```
https://github.com/Alfresco/alfresco-js-api/issues/357
Allows for sending credentials as part of a …
> Issue 357 Add support for withCredentials

- src/api-legacy/content-rest-api/src/api/nodesApi.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Returns the wrong type of the Node
Use the correct type of the Node …
> fix return value Type issue

- src/api/activiti-rest-api/api/report.api.ts
```
```
```
[x] Bugfix
[ ] Feature
```
https://issues.alfresco.com/jira/browse/ADF-4071 …
> [ADF-4071] ReportApi - Add "__reportName" property into queryParams

- src/alfrescoApi.ts
- src/alfrescoApiClient.ts
- src/api-legacy/activiti-rest-api/src/api/ProcessApi.ts
- src/api-legacy/activiti-rest-api/src/api/ProcessDefinitionsFormApi.ts
- src/api/activiti-rest-api/api/processDefinitions.api.ts
- src/api/activiti-rest-api/api/taskForms.api.ts
- test/alfrescoApiClient.spec.ts
```
```
```
[x] Bugfix
[ ] Feature
```
https://issues.alfresco.com/jira/browse/ADF-4075 …
> [ADF-4075] TaskFormsApi - change getRestFieldValues return format

- src/authentication/oauth2Auth.ts
```
```
```
[x] Bugfix
[ ] Feature
```
In the settings, put the SSO config with implicitFlow set to false
Click Apply
Login
Current behaviour:
User is not able to log in
"SSO Authentication server is unreachable" is displayed
In the local storage, …
> [ADF-4220] avoid store discovery service information

- src/api-legacy/content-rest-api/src/api/peopleApi.ts
```
```
```
[x] Bugfix
[ ] Feature
```
fix groups api issue
```
[ ] Yes
[x] …
```
> fix groups api initialiser

- api-codegen/src/main/resources/api-code-gen/apis.mustache
```
```
```
[x] Bugfix
[ ] Feature
```
Code generation throws error when trying to add a new api
Template for index.ts is fixed.
**Does this PR …
> Fix template problem in api code generation

- package-lock.json
- src/alfrescoApi.ts
- src/alfrescoApiClient.ts
- src/api-legacy/content-rest-api/src/api/changesApi.ts
- src/api-legacy/content-rest-api/src/api/renditionsApi.ts
- src/authentication/processAuth.ts
- test/auth.spec.ts
- test/bpmAuth.spec.ts
- test/content-services/groupsApi.spec.ts
- test/ecmAuth.spec.ts
- test/oauth2Auth.spec.ts
- test/oauth2AuthImplicitFlow.spec.ts
- test/process-services/profileApi.ts
- test/process-services/taskApi.spec.ts
- tsconfig.base.json
- tsconfig.json
- tslint.json
```
```
```
[x] Bugfix
[ ] Feature
```
- fix issue with renditions api not passing the opts param
- update package-lock
- enforce noUnusedLocals …
> fix rendition api, enforce extra rules

- README.md
- package.json
- src/authentication/oauth2Auth.ts
- src/authentication/oauth2Config.ts
- test/oauth2Auth.spec.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> Implement SilentLoginExceptList

- README.md
- src/authentication/oauth2Auth.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
https://issues.alfresco.com/jira/browse/ADF-4924 …
> [ADF-4924] SSO refresh token timeout default value

- src/authentication/oauth2Auth.ts
- test/oauth2Auth.spec.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> [ADF-4810] check publicUrls is array object

- .travis.yml
- README.md
- package-lock.json
- scripts/trigger-travis.sh
```
```
```
[ ] Bugfix
[ ] Feature
```
This PR will allow to trigger an ADF build when JS-API change …
> trigger ADF build from JS-API

- src/api/activiti-rest-api/api/report.api.ts
```
```
```
[x] Bugfix
[ ] Feature
```
- fix report api parameter types
```
[ …
```
> type fixes

- src/alfrescoApiClient.ts
- src/alfrescoApiConfig.ts
- src/api/gs-core-rest-api/model/unfiledRecordFolderChild.ts
- src/api/search-rest-api/model/resultNode.ts
- src/authentication/authentication.ts
- src/authentication/basicAuth.ts
- src/authentication/contentAuth.ts
- src/authentication/oauth2.ts
- src/authentication/oauth2Auth.ts
- src/authentication/oauth2Config.ts
- src/authentication/processAuth.ts
- src/contentClient.ts
- src/processClient.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
- use interfaces over classes for internal auth (reduces bundle size as not generated into JS classes)
- …
> Minor changes for better type safety

- package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
- validate minified and gzipped bundle, use 55KB threshold
- remove old contributors list from …
> check minified and gzipped bundle

- .editorconfig
- README.md
- api-codegen/pom.xml
- api-codegen/src/main/resources/api-code-gen/api_doc.mustache
- api-codegen/src/main/resources/api-code-gen/modelGeneric.mustache
- api-codegen/src/main/resources/api-code-gen/model_doc.mustache
- api-codegen/src/main/resources/api-code-gen/readmeIndex.mustache
- pom.xml
- src/api/auth-rest-api/README.md
- src/api/auth-rest-api/docs/AuthenticationApi.md
- src/api/content-rest-api/README.md
- src/api/discovery-rest-api/README.md
- src/api/discovery-rest-api/docs/DiscoveryApi.md
```
```
```
[ ] Bugfix
[ ] Feature
```
- improve templates for the docs
- update readme with ES6 examples
- simplify various sections
- fix …
> documentation fixes

- .travis.yml
- scripts/build.sh
- scripts/git-tag-beta.sh
- scripts/publish.sh
```
```
```
[ ] Bugfix
[ ] Feature
```
Move release task in travis
```
[ ] …
```
> [ADF-4844] Move JS-API release in travis

- package-lock.json
- package.json
- src/alfrescoApiClient.ts
- test/process-services/taskFormApi.spec.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
- upgrade to the latest superagent/nock libs
- upgrade the code to align with breaking changes of the …
> upgrade to latest superagent and nock libs

- .travis.yml
- package-lock.json
- package.json
- scripts/build.sh
- scripts/publish.sh
- scripts/test-integration.sh
- test/integration/test-node/login-bpmn.ts
- test/process-services/taskFormApi.spec.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Last alpha is not able to log in in the BPMN
- First step a new test is going to check the login in the …
> Add bpmn test

- package-lock.json
- package.json
- src/authentication/oauth2Auth.ts
- test/mockObjects/oauth2/authResponseMock.js
- test/oauth2Auth.spec.ts
- test/oauth2AuthImplicitFlow.spec.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
Remove discovery phase for improve performance …
> Remove discovery phase

- src/alfrescoApi.ts
- src/authentication/oauth2Auth.ts
```
```
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
Promote use async await
remove unused call …
> Promote use await async

- .make-packages.js
- README.md
- package.json
- scripts/build.sh
- scripts/test-build.sh
```
```
```
[ ] Bugfix
[ ] Feature
```
- remove `devDependencies` and other fields from the `package.json` that gets published to NPM
- do not …
> cleanup package before publishing

- README.md
```
```
```
[ ] Bugfix
[ ] Feature
```
Update doc
```
[ ] Yes
[ ] No
```
If …
> Add Old link documentation AP1

- src/authentication/oauth2Auth.ts
```
```
```
[x] Bugfix
[ ] Feature
```
[ADF-4993](https://issues.alfresco.com/jira/browse/ADF-4993) …
> [ADF-4993] User can stay logged in by continuously refreshing the page.

- src/authentication/oauth2Auth.ts
- test/mockObjects/oauth2/authResponseMock.js
- test/oauth2Auth.spec.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
New unit test to explicit document and test the oauth class behaviour …
> multiinstance test oauth test

- package-lock.json
```
```
```
[ ] Bugfix
[ ] Feature
```
Minor dev vulnerability fix founded with npm audit …
> fix minor vulnerability JS-API

- src/api/activiti-rest-api/api/content.api.ts
```
```
```
[X] Bugfix
[ ] Feature
```
Fix rendition APS interpolation 1.x …
> [ADF-5027] Fix rendition APS 1.X

- src/api/content-rest-api/api/customModel.api.ts
- src/api/content-rest-api/api/index.ts
```
```
```
[x] Bugfix
[ ] Feature
```
- add missing export for model api
- add missing `author` parameter …
> add missing export and parameter for model api

- src/alfrescoApiClient.ts
- src/api/activiti-rest-api/api/content.api.ts
```
```
```
[X] Bugfix
[ ] Feature
```
fix blob rendition APS 1.X
```
[ ] Yes …
```
> [ADF-5025] fix blob rendition APS 1.X

- package.json
- src/alfrescoApi.ts
- src/alfrescoApiClient.ts
- src/authentication/contentAuth.ts
- src/authentication/oauth2Auth.ts
- src/authentication/processAuth.ts
- src/storage.ts
```
```
```
[ ] Bugfix
[x] Feature
```
The prefix was used only in the CS auth now is everywhere we use the storage …
> [ADF-4980] Extent the prefix use evrywhere

- src/api/content-rest-api/api/classes.api.ts
```
```
```
[ ] Bugfix
[x] Feature
```
add a mapping for the "subclasses" private api, that should allow implementing "create custom type" and …
> add missing subclasses api

- .travis.yml
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> Update .travis.yml node version

- src/api/content-rest-api/api/customModel.api.ts
```
```
```
[ ] Bugfix
[x] Feature
```
add missing "deleteAspect" api
```
[ ] …
```
> add missing "deleteCustomAspect" api

- src/api/content-rest-api/api/customModel.api.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
- remove useless 'aspectName' parameter (not used by ADF for the moment, so not a breaking change)
- use …
> correct "add property to type" api

- src/api/content-rest-api/api/customModel.api.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
- add missing typings for custom models api …
> update custom model api fixes

- src/alfrescoApi.ts
```
```
```
[ ] Bugfix
[x] Feature
```
Allows to reuse the isPublicUrl from js-api inside of content-store …
> [ACA-2755] sso public url

- src/authentication/processAuth.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
remove `console.log` from auth code …
> remove console.log from the auth

- src/api/content-rest-api/docs/AuditApi.md
```
```
```
[ ] Bugfix
[ ] Feature
```
The table written in Markdown format is broken.
Tables written in Markdown format are displayed …
> Fix tables written in markdown.

- src/api/activiti-rest-api/api/processInstances.api.ts
```
```
```
[x] Bugfix
[ ] Feature
```
https://issues.alfresco.com/jira/browse/AAE-2041
done …
> [AAE-2041] [APS-1] [ADF] download process audit log not working

- src/api/activiti-rest-api/model/systemPropertiesRepresentation.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> add additional property to SystemProperties

- .travis.yml
- scripts/build.sh
- scripts/publish.sh
- scripts/update-project.sh
```
```
```
[ ] Bugfix
[ ] Feature
```
Prepare script to change name development to develop …
> [AAE-2571] Prepare script to change name development to develop

- src/authentication/oauth2Auth.ts
- test/alfrescoApi.spec.ts
- test/alfrescoContent.spec.ts
- test/content-services/commentsApi.spec.ts
- test/content-services/customModelApi.spec.ts
- test/content-services/groupsApi.spec.ts
- test/content-services/nodeApi.spec.ts
- test/content-services/peopleApi.spec.ts
- test/content-services/queriesApi.spec.ts
- test/content-services/renditionApi.spec.ts
- test/content-services/tagApi.spec.ts
- test/content-services/versionsApi.spec.ts
- test/content-services/webScriptApi.spec.ts
- test/discoveryApi.spec.ts
- test/ecmAuth.spec.ts
- test/governance-services/gsSitesApi.spec.ts
- test/integration/test-node/upload-file.ts
- test/mockObjects/content-services/commentMock.js
- test/oauth2Auth.spec.ts
- test/oauth2AuthImplicitFlow.spec.ts
- test/peopleApi.spec.ts
- test/process-services/modelApi.spec.ts
- test/process-services/modelJsonBpmnApi.spec.ts
- test/process-services/profileApi.ts
- test/process-services/userFiltersApi.spec.ts
- test/searchApi.spec.spec.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
- reduce the need for compatibility layer for certain scenarios …
> reduce JS compatibility layer

- src/alfrescoApiConfig.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Improve init in case of an empty constructor parameter …
> improve init constructor config

- src/api/content-rest-api/api/versions.api.ts
- src/api/content-rest-api/docs/VersionsApi.md
- test/content-services/versionsApi.spec.ts
- test/mockObjects/content-services/versionMock.js
```
[x ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-js-api/wiki/Commit-format)
[x ] Docs have been added / updated (for bug fixes / features)
```
```
[ ] Bugfix
[x ] Feature
```
https://issues.alfresco.com/jira/browse/ADF-5144
incrementally update Alfresco JS APIs for …
> [ADF-5144] Update JS Renditions API for new version endpoints / capabilities

- package-lock.json
- package.json
- tools/rollup-bundle.js
- tsconfig.base.json
```
```
```
[ ] Bugfix
[ ] Feature
```
- cleanup some scripts
```
[ ] Yes
[x] …
```
> reduce scripts

- src/authentication/oauth2Auth.ts
- tsconfig.base.json
```
```
```
[ ] Bugfix
[ ] Feature
```
extra fixes for old typescript compatibility …
> add compatibility with older typescript

- package-lock.json
- package.json
- test/mockObjects/content-services/customModelMock.js
- tsconfig.base.json
```
```
```
[ ] Bugfix
[ ] Feature
```
- upgrade nock and fix failing test …
> upgrade nock and fix tests

- src/authentication/oauth2Auth.ts
- test/oauth2AuthImplicitFlow.spec.ts
```
```
```
[X] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> [MNT-21636] - adding to local storage the redirect url for sso

- src/authentication/oauth2Auth.ts
- test/oauth2AuthImplicitFlow.spec.ts
```
```
```
[X] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> Fixed redirection fragment for DW

- src/alfrescoApi.ts
- test/alfrescoApiClient.spec.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Store username for node use
```
[ ] …
```
> Store username for node use

- definitions/alfresco-core.yaml
- src/api/content-rest-api/docs/SiteMembershipRequestBodyCreate.md
- src/api/content-rest-api/model/siteMembershipRequestBodyCreate.ts
```
```
```
[ ] Bugfix
[x] Feature
```
https://alfresco.atlassian.net/browse/ACS-880 …
> [ACS-880] Enable digital-work-space to join link to site with workspace template

- src/authentication/oauth2Auth.ts
```
```
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
Remove not needed async
```
[ ] Yes
[ …
```
> Remove not needed async

- src/authentication/oauth2Auth.ts
- test/integration/test-node/login-bpmn.ts
- test/integration/test-node/login-sso.ts
- test/oauth2Auth.spec.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Fix refresh token for node env
```
[ ] …
```
> Fix refresh token for node env

- src/authentication/oauth2Auth.ts
```
```
```
[x] Bugfix
[ ] Feature
```
handle promise refresh
```
[ ] Yes
[ ] …
```
> handle promise refresh

- .travis.yml
- scripts/update-project.sh
```
```
```
[x] Bugfix
[ ] Feature
```
Create PR to update JS-API on ADF
``` …
```
> Create PR to update JS-API on ADF

- src/alfrescoApi.ts
- src/authentication/oauth2Auth.ts
- test/integration/test-node/login-sso.ts
- test/oauth2Auth.spec.ts
- test/oauth2AuthImplicitFlow.spec.ts
```
```
```
[x] Bugfix
[ ] Feature
```
fix missing handled promise alf ticket …
> fix missing handled promise alf ticket

- src/alfrescoApi.ts
- test/alfrescoApi.spec.ts
- test/auth.spec.ts
```
```
```
[ ] Bugfix
[x] Feature
```
Clear message for missing login parameters …
> [ADF-5325] Clear message for missing login parameters

- src/authentication/oauth2Auth.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Fix refresh token to use formParams …
> Fix refresh token to use formParams

- .travis.yml
- scripts/pr-creator.js
- scripts/update-project.sh
```
```
```
[x] Bugfix
[ ] Feature
```
New update script
```
[ ] Yes
[ ] No …
```
> New update script

- definitions/alfresco-model.yaml
- src/api/model-rest-api/README.md
- src/api/model-rest-api/api/aspects.api.ts
- src/api/model-rest-api/api/index.ts
- src/api/model-rest-api/api/types.api.ts
- src/api/model-rest-api/docs/AspectsApi.md
- src/api/model-rest-api/docs/Type.md
- src/api/model-rest-api/docs/TypeEntry.md
- src/api/model-rest-api/docs/TypePaging.md
- src/api/model-rest-api/docs/TypePaging_list.md
- src/api/model-rest-api/docs/TypesApi.md
- src/api/model-rest-api/model/abstractClass.ts
- src/api/model-rest-api/model/aspect.ts
- src/api/model-rest-api/model/index.ts
- src/api/model-rest-api/model/type.ts
- src/api/model-rest-api/model/typeEntry.ts
- src/api/model-rest-api/model/typePaging.ts
- src/api/model-rest-api/model/typePagingList.ts
- src/authentication/oauth2Auth.ts
```
```
```
[ ] Bugfix
[x] Feature
```
Exposed Type API
depends https://github.com/Alfresco/rest-api-explorer/pull/119
**Does this PR introduce …
> [REPO-5552] Expose Type API

- definitions/alfresco-model.yaml
- src/api/model-rest-api/README.md
- src/api/model-rest-api/api/aspects.api.ts
- src/api/model-rest-api/api/types.api.ts
- src/api/model-rest-api/docs/Aspect.md
- src/api/model-rest-api/docs/AspectsApi.md
- src/api/model-rest-api/docs/Model.md
- src/api/model-rest-api/docs/Type.md
- src/api/model-rest-api/docs/TypesApi.md
- src/api/model-rest-api/model/model.ts
```
```
```
[ ] Bugfix
[x] Feature
```
Model information will be available as part the aspect/type …
> [REPO-5552] show model info for the aspect/type

- scripts/update-project.sh
```
```
```
[x] Bugfix
[ ] Feature
```
https://alfresco.atlassian.net/browse/ADF-5338
This PR changes the update-project.sh script to update …
> [ADF-5338] Update peer dependencies on projects

- test/upload.spec.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> Fix spec Upload for new TS version

- src/alfrescoApiClient.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
Make JS-API works on stackblitz
```
[ …
```
> Make JS-API works on stackblitz

- src/alfrescoApiClient.ts
Reverts Alfresco/alfresco-js-api#1009
> Revert "Make JS-API works on stackblitz"

- src/alfrescoApiClient.ts
- src/authentication/oauth2Auth.ts
- test/oauth2Auth.spec.ts
```
```
```
[x] Bugfix
[ ] Feature
```
https://alfresco.atlassian.net/browse/ACA-4317
fixed …
> [ACA-4317][JS-API] CS silent refresh is not working for content service

- package-lock.json
- package.json
- test/performance/test-webpack/package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
remove `rimraf` that is no longer used anywhere …
> remove unused rimraf dependency

- package-lock.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> update audit fix

- scripts/generate-reports.sh
```
```
```
[ ] Bugfix
[x] Feature
```
generate release reports
```sh
./scripts/generate-reports.sh
```
produces:
- 3rd party license report
- …
> [ACS-2197] release reports generation

- README.md
- src/authentication/oauth2Auth.ts
- src/authentication/oauth2Config.ts
- test/oauth2Auth.spec.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> Support custom OAuth endpoints

- src/api/gs-classification-rest-api/api/securityMarks.api.ts
- test/governance-services/securityMarksApi.spec.ts
- test/mockObjects/goverance-services/security-marks.mock.ts
```
```
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
If this PR …
> Changes on create security marks endpoint

- package-lock.json
- package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> revert superagent

- .travis.yml
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> Make ADF possible to update on request

- docs/audit/audit-info-4.9.0.md
- docs/changelog/changelog-4.9.0.md
- docs/licences/license-info-4.9.0.md
- package-lock.json
- package.json
- scripts/generate-reports.sh
```
```
```
[ ] Bugfix
[ ] Feature
```
update version to 4.9.0
generate reports
update the changelog generation script
**Does this PR introduce …
> Release 4.9.0

- docs/audit/audit-info-4.10.0.md
- docs/changelog/changelog-4.10.0.md
- docs/licences/license-info-4.10.0.md
- package-lock.json
- package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
Project changes for 4.10.0 release
``` …
```
> Release 4.10.0

- src/authentication/oauth2Auth.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> [AAE-8649] SSO grant type password - Ability to pass client secret

- src/authentication/oauth2Auth.ts
- test/oauth2Auth.spec.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> [AAE-8649] Being able to use input values of discovery

- .github/workflows/js-api-build.yml
- .github/workflows/trigger-upstream.yml
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> Create a different flow for upstream manually

- src/authentication/oauth2Auth.ts
- src/authentication/oauth2Config.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> [AAE-8750] OAuth - Expose the api to fetch userinfo

- docs/audit/audit-info-4.11.0.md
- docs/changelog/changelog-4.11.0.md
- docs/licences/license-info-4.11.0.md
- package-lock.json
- package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
release changes for 4.11.0
```
[ ] Yes …
```
> [ACS-3107] release 4.11.0

- src/api-clients/api-client.ts
https://alfresco.atlassian.net/browse/AAE-10200
> Fix the order of httpClient testing conditions

- docs/audit/audit-info-5.0.0.md
- docs/changelog/changelog-5.0.0.md
- docs/licences/license-info-5.0.0.md
- package-lock.json
- package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
release activities for 5.0.0
```
[ ] …
```
> Release 5.0.0

- src/api/gs-classification-rest-api/model/securityGroup.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> APPS-1647-Added-system-group-attribute-in-security-group-get-api

- src/alfrescoApiClient.ts
- src/superagentHttpClient.ts
```
```
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
If this PR …
> [ADF-5501] fix: change the guard for progress event detection

- docs/audit/audit-info-5.1.0.md
- docs/changelog/changelog-5.1.0.md
- docs/licences/license-info-5.1.0.md
- package-lock.json
- package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
5.1.0 release steps
```
[ ] Yes
[x] No …
```
> [ACS-3839] Release 5.1.0

- docs/audit/audit-info-5.2.0.md
- docs/changelog/changelog-5.2.0.md
- docs/licences/license-info-5.2.0.md
- package-lock.json
- package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
5.2.0 release steps
```
[ ] Yes
[x] No …
```
> [AAE-11663] Release 5.2.0

- src/api/content-rest-api/api/index.ts
```
```
```
[ ] Bugfix
[x] Feature
```
Categories api is not exported.
Categories api is exported and can be used. …
> [ACS-4114] Export categories api

- src/api/content-rest-api/api/categories.api.ts
- src/api/content-rest-api/docs/CategoriesApi.md
```
```
```
[x] Bugfix
[ ] Feature
```
API delete endpoint was wrong
API delete endpoint did correct. …
> [ACS-4240] delete category api change

- .github/workflows/codeql-analysis.yml
```
```
```
[ ] Bugfix
[ ] Feature
```
Upgrade CodeQL before it is deprecated (https://github.blog/changelog/2022-04-27-code-scanning-deprecation …
> [ACS-4413] upgrade CodeQL to v2

- src/api/content-rest-api/README.md
- src/api/content-rest-api/api/tags.api.ts
- src/api/content-rest-api/docs/TagsApi.md
```
```
```
[ ] Bugfix
[x] Feature
```
https://alfresco.atlassian.net/browse/ACS-4118
Added function to create tags without node and to load …
> [ACS-4118] create a tag from tags list

- docs/audit/audit-info-5.3.0.md
- docs/changelog/changelog-5.3.0.md
- docs/licences/license-info-5.3.0.md
- package-lock.json
- package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
Version bump and release reports for 5.3.0 …
> Release of 5.3.0

- test/content-services/tagApi.spec.ts
- test/mockObjects/content-services/tag.mock.ts
```
```
```
[ ] Bugfix
[ ] Feature
Unit tests added 
```
https://alfresco.atlassian.net/browse/ACS-4412
Unit tests added 
**Does this PR …
> [ACS-4412] Unit tests for createTags function

- .github/workflows/js-api-build.yml
```
```
```
[ ] Bugfix
[ ] Feature
```
Integration tests are failing with the login issues
disable Integration tests until the issues with login …
> [ADF-5515] disable integration tests until config fixes

- docs/audit/audit-info-5.4.0.md
- docs/changelog/changelog-5.4.0.md
- docs/licences/license-info-5.4.0.md
- package-lock.json
- package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> Release of 5.4.0

- .make-packages.js
- package-lock.json
- package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
https://alfresco.atlassian.net/browse/ACS-4723
Removed `fs-extra` dependency and instead used built-in …
> [ACS-4723] Remove fs-extra dependency

- README.md
- docs/licences/license-info-5.1.0.md
- package-lock.json
- package.json
- src/authentication/oauth2Auth.ts
- src/utils/path-matcher.ts
- test/oauth2Auth.spec.ts
- test/path-matcher.spec.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
https://alfresco.atlassian.net/browse/ACS-4724
Minimatch dependency has been removed. Needed logic has …
> [ACS-4724] remove minimatch dependency

- .github/workflows/js-api-build.yml
- scripts/publish.sh
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> Publish js pkg on gh pkg registry [Do Not merge]

- .github/workflows/js-api-build.yml
- scripts/publish.sh
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> Rely on action to create npmrc

- .github/workflows/js-api-build.yml
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> Inverte release order

- .github/workflows/js-api-build.yml
- test/integration/test-node/login-ecm.ts
- test/integration/test-node/login-sso.ts
- test/integration/test-node/node-content.ts
- test/integration/test-node/upload-file.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Integration test for js api is not working
Integration test for js api is working
**Does this PR …
> [ADF-5515] Integration test for js api working

- src/api/content-rest-api/api/categories.api.ts
- src/api/content-rest-api/docs/CategoriesApi.md
- test/content-services/categoriesApi.spec.ts
```
```
```
[ ] Bugfix
[ ] Feature
[X] Code style update (formatting, local variables)
```
Return type is incorrect.
Changed return type & function naming to be more clear.
**Does this PR …
> [ACS-4117] Creating multiple subcategories

- docs/audit/audit-info-5.5.0.md
- docs/changelog/changelog-5.5.0.md
- docs/licences/license-info-5.5.0.md
- package-lock.json
- package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> Release of 5.5.0

- .github/workflows/js-api-build.yml
- .gitignore
- test/integration/test-node/login-ecm.ts
- test/integration/test-node/node-content.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
split testing jobs to run in parallel
add error reporting for integration tests
**Does this PR introduce …
> split testing jobs and add error reporting

- .github/workflows/js-api-build.yml
- scripts/create-tag.js
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> [AAE-13902] - Create the tag using actions

- definitions/activiti-api.json
```
```
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
There was one left reference to Alfresco. 
Renamed that left reference to Alfresco to Hyland. 
**Does …
> [ACS-5040] Renamed one left reference to Alfresco

- docs/audit/audit-info-6.0.0.md
- docs/changelog/changelog-6.0.0.md
- docs/licences/license-info-6.0.0.md
- package-lock.json
- package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
release reports and version bump for 6.0.0 …
> [ACS-5126] Release 6.0.0

- docs/audit/audit-info-6.1.0.md
- docs/changelog/changelog-6.1.0.md
- docs/licences/license-info-6.1.0.md
- package-lock.json
- package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this PR …
> [AAE-14434] Release 6.1.0

- src/api/content-rest-api/api/nodes.api.ts
```
```
```
[x] Bugfix
[ ] Feature
```
https://github.com/Alfresco/alfresco-js-api/issues/380
add missing query params for pagination for target …
> fix child assocs pagination

- src/superagentHttpClient.ts
- test/superagentHttpClient.spec.ts
```
```
```
[x] Bugfix
[ ] Feature
```
https://github.com/Alfresco/alfresco-js-api/issues/406
- do not encode basic auth credentials as URI, …
> do not escape basic auth credentials

- docs/audit/audit-info-6.2.0.md
- docs/changelog/changelog-6.2.0.md
- docs/licences/license-info-6.2.0.md
- package-lock.json
- package.json
```
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe:
```
Release 6.2.0
```
[ ] Yes
[X] No
``` …
> Release 6.2.0

- package-lock.json
- package.json
- test/integration/test-node/tsconfig.json
- test/performance/test-webpack/tsconfig.json
- tsconfig/tsconfig.esm5.json
```
```
```
[ ] Bugfix
[ ] Feature
```
bump superagent
```
[ ] Yes
[ ] No
``` …
> bump superagent

- src/api/activiti-rest-api/model/formDefinitionRepresentation.ts
- src/api/activiti-rest-api/model/formFieldRepresentation.ts
- src/api/activiti-rest-api/model/formJavascriptEventRepresentation.ts
- src/api/activiti-rest-api/model/formOutcomeRepresentation.ts
- src/api/activiti-rest-api/model/formTabRepresentation.ts
- src/api/activiti-rest-api/model/formVariableRepresentation.ts
- src/api/activiti-rest-api/model/optionRepresentation.ts
```
```
```
[x] Bugfix
[ ] Feature
```
- add missing `fields` property to the `FormFieldRepresentation`
- make `FormFieldRepresentation` more …
> Fix FormFieldRepresentation typings, add missing "fields" property

- src/alfrescoApi.ts
- src/authentication/contentAuth.ts
- src/authentication/oauth2Auth.ts
- src/authentication/processAuth.ts
- test/auth.spec.ts
- test/bpmAuth.spec.ts
- test/ecmAuth.spec.ts
```
```
```
[x] Bugfix
[ ] Feature
```
- remove `console.log` and return proper promise rejections; fixes #1363
- update various return types to …
> Remove console logs from auth and fix promise rejections

- definitions/activiti-api.json
- src/api/activiti-rest-api/README.md
- src/api/activiti-rest-api/api/content.api.ts
- src/api/activiti-rest-api/docs/ContentApi.md
- src/api/activiti-rest-api/docs/RelatedProcessTask.md
- src/api/activiti-rest-api/model/relatedProcessTask.ts
```
```
```
[ ] Bugfix
[x] Feature
```
API to fetch processes and tasks related to content that workflow was started with has been added. …
> [ACS-5601] Add related content API

- src/api/content-rest-api/api/trashcan.api.ts
```
```
```
[x] Bugfix
[ ] Feature
```
- various typings fixes
```
[ ] Yes …
```
> [ACS-5839] typing fixes

- src/api/gs-classification-rest-api/api/authorityClearance.api.ts
- src/api/gs-classification-rest-api/api/classificationGuides.api.ts
- src/api/gs-classification-rest-api/api/classificationReasons.api.ts
- src/api/gs-classification-rest-api/api/declassificationExemptions.api.ts
- src/api/gs-classification-rest-api/api/index.ts
- src/api/gs-classification-rest-api/api/nodeSecurityMarks.api.ts
- src/api/gs-classification-rest-api/api/securityGroups.api.ts
- src/api/gs-classification-rest-api/api/securityMarks.api.ts
- src/api/gs-classification-rest-api/api/types.ts
```
```
```
[x] Bugfix
[ ] Feature
```
- improved typing for GS api
- remove parameters from GS that are not supported
- add missing paging …
> [ACS-5839] GS Api enhancements and typings

- src/api/activiti-rest-api/api/comments.api.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Adding comments to task uses wrong http method.
Adding comments to task correctly uses post now.
**Does …
> Fix adding comments to task

- docs/audit/audit-info-7.0.0.md
- docs/changelog/changelog-7.0.0.md
- docs/licences/license-info-7.0.0.md
```
```
```
[ ] Bugfix
[ ] Feature
```
- release reports and version bump
``` …
```
> Release 7.0.0

- definitions/activiti-api.json
- src/api/activiti-rest-api/api/content.api.ts
- src/api/activiti-rest-api/docs/ContentApi.md
```
```
```
[ ] Bugfix
[ ] Feature
[X] Code style update (formatting, local variables)
```
Wrong endpoint 
Updated endpoint from `document-details` to `document-runtime` in order to align with …
> [ACTIVITI-4914] Update getProcessesAndTasksOnContent

- definitions/activiti-api.json
- src/api/activiti-rest-api/api/content.api.ts
- src/api/activiti-rest-api/docs/ContentApi.md
- src/api/activiti-rest-api/docs/ResultListDataRepresentationRelatedProcessTask.md
- src/api/activiti-rest-api/model/resultListDataRepresentationRelatedProcessTask.ts
```
```
```
[ ] Bugfix
[x] Feature
```
getProcessesAndTasksOnContent has been modified to reflect latest BE changes. …
> [ACTIVITI-4914] Adjust getProcessesAndTasksOnContent to latest BE changes

- package-lock.json
- package.json
- test/oauth2Auth.spec.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
- remove `mocha-jsdom` dependency as it is no longer maintained and triggers multiple security issues
- …
> [ACA-4724] remove mocha-jsdom dependency due to security issues

- src/api/activiti-rest-api/api/content.api.ts
```
```
```
[ ] Bugfix
[x] Feature
```
Adjusted endpoint path for getProcessesAndTasksOnContent method after BE changes.
**Does this PR …
> [ACTIVITI-4914] Adjust related process and tasks content endpoint

- src/api/content-rest-api/api/nodes.api.ts
- src/api/content-rest-api/docs/NodesApi.md
- test/content-services/nodeApi.spec.ts
- test/mockObjects/content-services/node.mock.ts
```
```
```
[ ] Bugfix
[X] Feature
```
https://alfresco.atlassian.net/browse/ACS-5994
JS-API now provides a method to delete multiple nodes …
> [ACS-5994] Add multiple nodes deletion support

- docs/audit/audit-info-7.1.0.md
- docs/changelog/changelog-7.1.0.md
- docs/licences/license-info-7.1.0.md
- package-lock.json
- package.json
```
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Release PR
```
Release PR for 7.1.0
```
[ …
```
> Release 7.1.0

- docs/audit/audit-info-7.2.0.md
- docs/changelog/changelog-7.2.0.md
- docs/licences/license-info-7.2.0.md
- package-lock.json
- package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
https://alfresco.atlassian.net/browse/AAE-17070
Release PR for 7.2.0 …
> Release 7.2.0
